### ISSUE TITLE
Linux: undefined reference to `terminal_font8'

### ISSUE THREAD

**Issue by denizzzka** [Elronnd/bearlibterminal-dlang#4]
```
bearlibterminal/source/terminal.d:232: undefined reference to `terminal_font8'
```

**Comment by moon-chilled** [comment]
It works fine for me.  What version of bearlibterminal do you have, and what version of the wrapper?  How are you building?

**Comment by denizzzka** [comment]
I am use wrapper 1.5.2 and also tried ~master. Linking with .so from ./lib/ and also tried library binary from the official site.

**Comment by denizzzka** [comment]
It looks like #1 - probably, changes in the upstream

**Comment by moon-chilled** [comment]
Yes, except that it's [still there](https://bitbucket.org/cfyzium/bearlibterminal/src/4777de25066242deb1d4efd08ec199f5c794723f/Terminal/Source/BearLibTerminal.cpp?at=default&fileviewer=file-view-default#BearLibTerminal.cpp-188) in upstream.  If you comment out `void terminal_font8(const char*);` and `void font(string name) { terminal_font8(toStringz(name)); }` does it work?  Are you building with dub or manually?

**Comment by denizzzka** [comment]
> If you comment out void terminal_font8(const char*); and void font(string name) { terminal_font8(toStringz(name)); } does it work?

Yes

> Are you building with dub or manually?

With dub

**Comment by denizzzka** [comment]
Problem was on my side, sorry (since time of  #1 my /usr/local/lib contained old version of library binary)
Excuse for troubling!

**Comment by moon-chilled** [comment]
Alright, cool.  I noticed that you did a [static import](https://github.com/denizzzka/dlangui_bearlibterminal/blob/master/source/app.d#L3) of blt, which is mostly unnecessary since there's already a pseudo-namespace in a static struct.  If you want it to be called BT, how about `import BearLibTerminal: BT = terminal`?  Then you can just `BT.open()`, `BT.read()`, etc., without having to type `terminal` every time.

**Comment by denizzzka** [comment]
True. Thanks, I am will change it
